version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    depends_on:
      - php

  mysql:
    image: mysql:5.7.17
    container_name: sonia_mysql
    volumes:
      - ./db_data:/var/lib/mysql
      # - ./db_data/sonia_test_1.sql:/docker-entrypoint-initdb.d/datadump.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sonia_test_1
      MYSQL_USER: sonia
      MYSQL_PASSWORD: (TwwcIy3ww3LySy@
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command: mysqld --sql_mode=""
    # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: sonia_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8091:80

volumes:
  db_data: {}
