version : '3.9'

services:
#php
  php:
    build: .
    volumes: 
      - ./app:/var/www/html
    ports :
      - 9000:80 
#mysql
  mysql:
    image: mysql:latest

    container_name: arifoglu_mysql
    volumes:
      - ./db_data:/var/lib/mysql
  
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root      
#phpmyadmin
  phpmyadmin:

    depends_on:
      - mysql
    container_name: arifoglu_phpmyadmin

    image: phpmyadmin:latest
    restart: always
    ports:
      - 9001:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root

