version : '3.9'

services:
#php
  php:
    build: .
    volumes: 
      - ./app:/var/www/html 
    ports :
      - 8000:80   
#database
  db:
    image: mysql:latest
    container_name: arifoglu_mysql
    volumes:
      - ./tutorial3_mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  
    restart: always
    environment:
          MYSQL_ROOT_PASSWORD: arifoglu 
          MYSQL_DATABASE: db
          MYSQL_PASSWORD: arifoglu 
#phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest  
    container_name: arifoglu_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db 
      PMA_USER: root
      PMA_PASSWORD: arifoglu

