version : '3.9'

services:

#php
  php:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
        - ./app:/var/www/html  

# nginx
  nginx:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./app:/var/www/html
    depends_on:
        - php  

#mysql
  db:
    image: mysql:latest
    container_name: arifoglu_mysql
    volumes:
      - ./db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password  
    restart: always
    environment:
          MYSQL_ROOT_PASSWORD: arifoglu 
          MYSQL_DATABASE: db
          MYSQL_PASSWORD: arifoglu    
            
#phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest  
    container_name: arifoglu_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: db 
      PMA_USER: root
      PMA_PASSWORD: arifoglu
